LLVM: llvm::BasicBlock Class Reference
LLVM API Documentation
llvm::BasicBlock Class Reference
LLVM Basic Block Representation.
#include <BasicBlock.h>
Public Types
typedef iplist< Instruction > InstListType
typedef InstListType::iterator iterator
Instruction iterators...
typedef
InstListType::const_iterator const_iterator
Public Member Functions
LLVMContext & getContext () const
getContext - Get the context in which this basic block lives.
~BasicBlock ()
const Function * getParent () const
Function * getParent ()
TerminatorInst * getTerminator ()
const TerminatorInst * getTerminator () const
Instruction * getFirstNonPHI ()
const Instruction * getFirstNonPHI () const
Instruction * getFirstNonPHIOrDbg ()
const Instruction * getFirstNonPHIOrDbg () const
Instruction * getFirstNonPHIOrDbgOrLifetime ()
const Instruction * getFirstNonPHIOrDbgOrLifetime () const
iterator getFirstInsertionPt ()
const_iterator getFirstInsertionPt () const
void removeFromParent ()
void eraseFromParent ()
void moveBefore (BasicBlock *MovePos)
void moveAfter (BasicBlock *MovePos)
BasicBlock * getSinglePredecessor ()
const BasicBlock * getSinglePredecessor () const
BasicBlock * getUniquePredecessor ()
const BasicBlock * getUniquePredecessor () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
size_t size () const
bool empty () const
const Instruction & front () const
Instruction & front ()
const Instruction & back () const
Instruction & back ()
const InstListType & getInstList () const
InstListType & getInstList ()
ValueSymbolTable * getValueSymbolTable ()
getValueSymbolTable() - returns pointer to symbol table (if any)
void dropAllReferences ()
void removePredecessor (BasicBlock *Pred, bool DontDeleteUselessPHIs=false)
BasicBlock * splitBasicBlock (iterator I, const Twine &BBName="")
bool hasAddressTaken () const
void replaceSuccessorsPhiUsesWith (BasicBlock *New)
bool isLandingPad () const
LandingPadInst * getLandingPadInst ()
const LandingPadInst * getLandingPadInst () const
Static Public Member Functions
static BasicBlock * Create (LLVMContext &Context, const Twine &Name="", Function *Parent=0, BasicBlock *InsertBefore=0)
static iplist< Instruction >
BasicBlock::* getSublistAccess (Instruction *)
getSublistAccess() - returns pointer to member of instruction list
static bool classof (const BasicBlock *)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
Friends
class BlockAddress
class SymbolTableListTraits< BasicBlock, Function >
Detailed Description
LLVM Basic Block Representation.
This represents a single basic block in LLVM. A basic block is simply a container of instructions that execute sequentially. Basic blocks are Values because they are referenced by instructions such as branches and switch tables. The type of a BasicBlock is "Type::LabelTy" because the basic block represents a label to which a branch can jump.
A well formed basic block is formed of a list of non-terminating instructions followed by a single TerminatorInst instruction. TerminatorInst's may not occur in the middle of basic blocks, and must terminate the blocks. The BasicBlock class allows malformed basic blocks to occur because it may be useful in the intermediate stage of constructing or modifying a program. However, the verifier will ensure that basic blocks are "well formed".
Definition at line 70 of file BasicBlock.h.
Member Typedef Documentation
typedef InstListType::const_iterator llvm::BasicBlock::const_iterator
Definition at line 97 of file BasicBlock.h.
typedef iplist<Instruction> llvm::BasicBlock::InstListType
Definition at line 74 of file BasicBlock.h.
typedef InstListType::iterator llvm::BasicBlock::iterator
Instruction iterators...
Definition at line 96 of file BasicBlock.h.
Constructor & Destructor Documentation
BasicBlock::~BasicBlock ()
Definition at line 61 of file BasicBlock.cpp.
References llvm::iplist< NodeTy, Traits >::clear(), llvm::BlockAddress::destroyConstant(), dropAllReferences(), llvm::ConstantInt::get(), getContext(), llvm::Type::getInt32Ty(), llvm::ConstantExpr::getIntToPtr(), getParent(), llvm::Value::getType(), hasAddressTaken(), llvm::Value::replaceAllUsesWith(), llvm::Value::use_back(), and llvm::Value::use_empty().
Member Function Documentation
const Instruction& llvm::BasicBlock::back () const [inline]
Definition at line 198 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::back().
Referenced by AddBlockAndPredsToSet(), llvm::AliasAnalysis::canBasicBlockModify(), llvm::CloneAndPruneFunctionInto(), ComputePostOrders(), llvm::DeleteDeadBlock(), and FindDependencies().
Instruction& llvm::BasicBlock::back () [inline]
Definition at line 199 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::back().
iterator llvm::BasicBlock::begin () [inline]
Instruction iterator methods
Definition at line 189 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::begin().
Referenced by llvm::AliasSetTracker::add(), AddPHINodeEntriesForMappedBlock(), AddPredecessorToBlock(), AddReachableCodeToWorklist(), llvm::CodeMetrics::analyzeBasicBlock(), BlockIsSimpleEnoughToThreadThrough(), llvm::Interpreter::callFunction(), CanPropagatePredecessorsForPHIs(), checkCSEInPredecessor(), CheckForEscapingAllocas(), llvm::CloneAndPruneFunctionInto(), llvm::CloneBasicBlock(), CloneLoopBlocks(), createPHIsForSplitLoopExit(), cxxDtorIsEmpty(), llvm::DeleteDeadPHIs(), DeleteInstructionInBlock(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::DominatorTree::dominates(), dropAllReferences(), llvm::EliminateDuplicatePHINodes(), llvm::CodeExtractor::extractCodeRegion(), llvm::FindAvailableLoadedValue(), FindDependencies(), FindInitTrampolineFromBB(), llvm::CodeExtractor::findInputsOutputs(), FindLoopCounter(), FindPHIForConditionForwarding(), FindPHIToPartitionLoops(), llvm::SSAUpdaterTraits< SSAUpdater >::FindPredecessorBlocks(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::FoldSingleEntryPHINodes(), FoldTwoEntryPHINode(), llvm::Loop::getCanonicalInductionVariable(), llvm::MemoryDependenceAnalysis::getDependency(), getFirstNonPHI(), getFirstNonPHIOrDbg(), getFirstNonPHIOrDbgOrLifetime(), GetIfCondition(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::SCEVExpander::getOrInsertCanonicalInductionVariable(), llvm::MemoryDependenceAnalysis::getPointerDependencyFrom(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), HandleCallsInBlockInlinedThroughInvoke(), HoistThenElseCodeToIf(), llvm::InlineFunction(), llvm::InsertProfilingInitCall(), isBlockValidForExtraction(), isExistingPhi(), llvm::Loop::isLCSSAForm(), llvm::isSafeToLoadUnconditionally(), isTrivialLoopExitBlockHelper(), llvm::Value::isUsedInBasicBlock(), LLVMGetFirstInstruction(), LLVMGetLastInstruction(), LLVMGetPreviousInstruction(), MarkAliveBlocks(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), MergeEmptyReturnBlocks(), NegateValue(), llvm::SparseSolver::Print(), PushLoopPHIs(), removePredecessor(), llvm::RemovePredecessorAndSimplify(), removeUndefIntroducingPredecessor(), llvm::ProfileInfoT< FType, BType >::repair(), llvm::SCEVExpander::replaceCongruentIVs(), replaceSuccessorsPhiUsesWith(), RewriteUsesOfClonedInstructions(), llvm::LoadAndStorePromoter::run(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToCondBranch(), llvm::InstCombiner::SimplifyDivRemOfSelect(), llvm::SimplifyInstructionsInBlock(), llvm::simplifyLoopIVs(), llvm::SparseSolver::Solve(), SpeculativelyExecuteBB(), splitBasicBlock(), llvm::SplitBlockPredecessors(), llvm::SplitCriticalEdge(), llvm::SplitEdge(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::UnrollLoop(), UpdatePHINodes(), llvm::InstCombiner::visitPHINode(), and llvm::InstCombiner::visitStoreInst().
const_iterator llvm::BasicBlock::begin () const [inline]
Definition at line 190 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::begin().
static bool llvm::BasicBlock::classof (const BasicBlock *) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 216 of file BasicBlock.h.
static bool llvm::BasicBlock::classof (const Value * V) [inline, static]
Reimplemented from llvm::Value.
Definition at line 217 of file BasicBlock.h.
References llvm::Value::BasicBlockVal, and llvm::Value::getValueID().
static BasicBlock* llvm::BasicBlock::Create (LLVMContext & Context, const Twine & Name = "", Function * Parent = 0, BasicBlock * InsertBefore = 0) [inline, static]
Create - Creates a new BasicBlock. If the Parent parameter is specified, the basic block is automatically inserted at either the end of the function (if InsertBefore is 0), or before the specified basic block.
Definition at line 102 of file BasicBlock.h.
References llvm::ISD::BasicBlock.
Referenced by llvm::CloneBasicBlock(), convertMemSetToLoop(), convertTransferToLoop(), llvm::CodeExtractor::extractCodeRegion(), FoldCondBranchOnPHI(), INITIALIZE_PASS(), LLVMAppendBasicBlockInContext(), LLVMInsertBasicBlockInContext(), PerformHeapAllocSRoA(), llvm::JIT::runFunction(), llvm::UnifyFunctionExitNodes::runOnFunction(), SimplifyCondBranchToCondBranch(), splitBasicBlock(), splitBlockAndInsertIfThen(), llvm::SplitBlockPredecessors(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), TryToSimplifyUncondBranchWithICmpInIt(), and llvm::UnrollRuntimeLoopProlog().
void BasicBlock::dropAllReferences ()
dropAllReferences() - This function causes all the subinstructions to "let go" of all references that they are maintaining. This allows one to 'delete' a whole class at a time, even though there may be circular references... first all references are dropped, and all use counts go to zero. Then everything is delete'd for real. Note that no operations are valid on an object that has "dropped all references", except operator delete.
Definition at line 176 of file BasicBlock.cpp.
References begin(), end(), and llvm::ARM_PROC::I.
Referenced by ~BasicBlock().
bool llvm::BasicBlock::empty () const [inline]
Definition at line 195 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::empty().
Referenced by llvm::DeleteDeadBlock().
iterator llvm::BasicBlock::end () [inline]
Definition at line 191 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::end().
Referenced by llvm::AliasSetTracker::add(), AddReachableCodeToWorklist(), llvm::CodeMetrics::analyzeBasicBlock(), ChangeToUnreachable(), checkCSEInPredecessor(), CheckForEscapingAllocas(), llvm::CloneBasicBlock(), cxxDtorIsEmpty(), dropAllReferences(), FindDependencies(), llvm::CodeExtractor::findInputsOutputs(), FoldBlockIntoPredecessor(), llvm::FoldBranchToCommonDest(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), HandleCallsInBlockInlinedThroughInvoke(), isBlockValidForExtraction(), llvm::isInTailCallPosition(), llvm::Loop::isLCSSAForm(), isSafeAndProfitableToSinkLoad(), isTrivialLoopExitBlockHelper(), llvm::Value::isUsedInBasicBlock(), LLVMGetFirstInstruction(), LLVMGetLastInstruction(), LLVMGetNextInstruction(), LLVMPositionBuilder(), MarkAliveBlocks(), llvm::MergeBlockIntoPredecessor(), passingValueIsAlwaysUndefined(), llvm::SparseSolver::Print(), replaceSuccessorsPhiUsesWith(), RewriteUsesOfClonedInstructions(), llvm::LoadAndStorePromoter::run(), llvm::IRBuilderBase::SetInsertPoint(), llvm::SimplifyInstructionsInBlock(), llvm::SparseSolver::Solve(), SpeculativelyExecuteBB(), splitBasicBlock(), and TryToSinkInstruction().
const_iterator llvm::BasicBlock::end () const [inline]
Definition at line 192 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::end().
void BasicBlock::eraseFromParent ()
eraseFromParent - This method unlinks 'this' from the containing function and deletes it.
Definition at line 100 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), and getParent().
Referenced by llvm::CloneAndPruneFunctionInto(), llvm::DeleteDeadBlock(), FoldBlockIntoPredecessor(), llvm::InlineFunction(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), MergeEmptyReturnBlocks(), and llvm::TryToSimplifyUncondBranchFromEmptyBlock().
const Instruction& llvm::BasicBlock::front () const [inline]
Definition at line 196 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::front().
Referenced by llvm::AliasAnalysis::canBasicBlockModify(), llvm::SSAUpdaterTraits< SSAUpdater >::CreateEmptyPHI(), llvm::FoldBranchToCommonDest(), llvm::ProfileInfoT< FType, BType >::GetPath(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::MergeBlockIntoPredecessor(), MergeEmptyReturnBlocks(), removePredecessor(), llvm::RemovePredecessorAndSimplify(), llvm::ProfileInfoT< FType, BType >::repair(), llvm::UnifyFunctionExitNodes::runOnFunction(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), and TryToSimplifyUncondBranchWithICmpInIt().
Instruction& llvm::BasicBlock::front () [inline]
Definition at line 197 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::front().
LLVMContext & BasicBlock::getContext () const
getContext - Get the context in which this basic block lives.
Reimplemented from llvm::Value.
Definition at line 33 of file BasicBlock.cpp.
References llvm::Type::getContext(), and llvm::Value::getType().
Referenced by llvm::CloneBasicBlock(), llvm::ConstantFoldTerminator(), llvm::EmitFWrite(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::CodeExtractor::extractCodeRegion(), llvm::SimplifyFortifiedLibCalls::fold(), FoldCondBranchOnPHI(), llvm::IncrementCounterInBlock(), PerformHeapAllocSRoA(), splitBasicBlock(), llvm::SplitBlockPredecessors(), llvm::SplitLandingPadPredecessors(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::UnrollRuntimeLoopProlog(), and ~BasicBlock().
BasicBlock::iterator BasicBlock::getFirstInsertionPt ()
getFirstInsertionPt - Returns an iterator to the first instruction in this block that is suitable for inserting a non-PHI instruction. In particular, it skips all PHIs and LandingPad instructions.
Definition at line 170 of file BasicBlock.cpp.
References getFirstNonPHI().
Referenced by llvm::InstCombiner::DoOneIteration(), getFirstInsertionPt(), llvm::IncrementCounterInBlock(), OptimizeCmpExpression(), OptimizeNoopCopyExpression(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::SplitLandingPadPredecessors(), TryToSinkInstruction(), and llvm::ObjectSizeOffsetEvaluator::visitPHINode().
const_iterator llvm::BasicBlock::getFirstInsertionPt () const [inline]
Definition at line 146 of file BasicBlock.h.
References getFirstInsertionPt().
Instruction * BasicBlock::getFirstNonPHI ()
Returns a pointer to the first instructon in this block that is not a PHINode instruction. When adding instruction to the beginning of the basic block, they should be added before the returned value, not before the first instruction, which might be PHI. Returns 0 is there's no non-PHI instruction.
Definition at line 130 of file BasicBlock.cpp.
References begin().
Referenced by createPHIsForSplitLoopExit(), getFirstInsertionPt(), getFirstNonPHI(), getJumpThreadDuplicationCost(), getLandingPadInst(), llvm::InvokeInst::getLandingPadInst(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), and isLandingPad().
const Instruction* llvm::BasicBlock::getFirstNonPHI () const [inline]
Definition at line 126 of file BasicBlock.h.
References getFirstNonPHI().
Instruction * BasicBlock::getFirstNonPHIOrDbg ()
Definition at line 140 of file BasicBlock.cpp.
References begin().
Referenced by FindPHIForConditionForwarding(), getFirstNonPHIOrDbg(), SimplifyCondBranchToTwoReturns(), and llvm::InstCombiner::visitAllocaInst().
const Instruction* llvm::BasicBlock::getFirstNonPHIOrDbg () const [inline]
Definition at line 132 of file BasicBlock.h.
References getFirstNonPHIOrDbg().
Instruction * BasicBlock::getFirstNonPHIOrDbgOrLifetime ()
Definition at line 150 of file BasicBlock.cpp.
References begin(), llvm::dyn_cast(), and llvm::IntrinsicInst::getIntrinsicID().
Referenced by getFirstNonPHIOrDbgOrLifetime().
const Instruction* llvm::BasicBlock::getFirstNonPHIOrDbgOrLifetime () const [inline]
Definition at line 138 of file BasicBlock.h.
References getFirstNonPHIOrDbgOrLifetime().
const InstListType& llvm::BasicBlock::getInstList () const [inline]
getInstList() - Return the underlying instruction list container. You need to access it directly if you want to modify it currently.
Definition at line 204 of file BasicBlock.h.
Referenced by ChangeToUnreachable(), llvm::CloneAndPruneFunctionInto(), llvm::CloneBasicBlock(), CloneLoopBlocks(), llvm::BinaryOperator::Create(), createCallHelper(), createMalloc(), llvm::DeleteDeadBlock(), DeleteInstructionInBlock(), llvm::InstCombiner::DoOneIteration(), llvm::Instruction::eraseFromParent(), llvm::CodeExtractor::extractCodeRegion(), FoldBlockIntoPredecessor(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), FoldTwoEntryPHINode(), HandleCallsInBlockInlinedThroughInvoke(), HoistThenElseCodeToIf(), llvm::InlineFunction(), llvm::Instruction::insertAfter(), llvm::Instruction::insertBefore(), llvm::IRBuilderDefaultInserter< true >::InsertHelper(), llvm::InstCombiner::InsertNewInstBefore(), llvm::Instruction::Instruction(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), llvm::Instruction::moveBefore(), llvm::Instruction::removeFromParent(), removePredecessor(), llvm::ReplaceInstWithInst(), llvm::UnifyFunctionExitNodes::runOnFunction(), SpeculativelyExecuteBB(), splitBasicBlock(), llvm::SplitLandingPadPredecessors(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), and llvm::UnrollLoop().
InstListType& llvm::BasicBlock::getInstList () [inline]
Definition at line 205 of file BasicBlock.h.
LandingPadInst * BasicBlock::getLandingPadInst ()
getLandingPadInst() - Return the landingpad instruction associated with the landing pad.
Definition at line 366 of file BasicBlock.cpp.
References llvm::dyn_cast(), and getFirstNonPHI().
Referenced by llvm::InlineFunction(), and llvm::SplitLandingPadPredecessors().
const LandingPadInst * BasicBlock::getLandingPadInst () const
Definition at line 369 of file BasicBlock.cpp.
References llvm::dyn_cast(), and getFirstNonPHI().
const Function* llvm::BasicBlock::getParent () const [inline]
getParent - Return the enclosing method, or null if none
Definition at line 110 of file BasicBlock.h.
Referenced by llvm::ProfileInfoT< FType, BType >::addExecutionCount(), llvm::CodeMetrics::analyzeBasicBlock(), llvm::ProfileInfoT< FType, BType >::CalculateMissingEdge(), ChangeToUnreachable(), CheckForEscapingAllocas(), llvm::CloneBasicBlock(), CloneLoopBlocks(), llvm::ConstantFoldTerminator(), llvm::IRBuilderBase::CreateGlobalString(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::EmitFWrite(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), llvm::EmitUnaryFloatFnCall(), eraseFromParent(), llvm::CodeExtractor::extractCodeRegion(), FoldCondBranchOnPHI(), llvm::BlockAddress::get(), llvm::MMIAddrLabelMap::getAddrLabelSymbol(), getCommonReturnValue(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), llvm::MemoryDependenceAnalysis::getDependency(), llvm::ProfileInfoT< FType, BType >::getExecutionCount(), llvm::Trace::getFunction(), getFunctionForValue(), llvm::ValueEnumerator::getGlobalBasicBlockID(), llvm::MemoryDependenceAnalysis::getLoadLoadClobberFullWidthSize(), llvm::DOTGraphTraits< DomTreeNode * >::getNodeLabel(), llvm::DOTGraphTraits< RegionNode * >::getNodeLabel(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::MemoryDependenceAnalysis::getPointerDependencyFrom(), llvm::JIT::getPointerToBasicBlock(), getValueSymbolTable(), HandleByValArgument(), HandleInlinedInvoke(), llvm::InlineFunction(), isDynamicConstant(), llvm::SelectionDAGBuilder::isExportableFromCurrentBlock(), llvm::isInTailCallPosition(), llvm::AllocaInst::isStaticAlloca(), LLVMGetNextBasicBlock(), LLVMGetPreviousBasicBlock(), LLVMInsertBasicBlockInContext(), llvm::IntrinsicLowering::LowerToByteSwap(), moveAfter(), moveBefore(), NegateValue(), PerformHeapAllocSRoA(), llvm::Value::print(), PrintOps(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), llvm::ProfileInfoT< FType, BType >::removeBlock(), removeFromParent(), llvm::ProfileInfoT< FType, BType >::replaceAllUses(), ReplaceCallWith(), llvm::ProfileInfoT< FType, BType >::setExecutionCount(), SimplifyCondBranchToCondBranch(), splitBasicBlock(), llvm::ProfileInfoT< FType, BType >::splitBlock(), splitBlockAndInsertIfThen(), llvm::SplitBlockPredecessors(), llvm::SplitCriticalEdge(), llvm::ProfileInfoT< FType, BType >::splitEdge(), llvm::SplitLandingPadPredecessors(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSimplifyUncondBranchWithICmpInIt(), TryToSinkInstruction(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopProlog(), UpdateCallGraphAfterInlining(), llvm::MMIAddrLabelMap::UpdateForDeletedBlock(), useFuncSeen(), ValueDominatesPHI(), llvm::DominatorTree::verifyAnalysis(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitFPTrunc(), and ~BasicBlock().
Function* llvm::BasicBlock::getParent () [inline]
Definition at line 111 of file BasicBlock.h.
BasicBlock * BasicBlock::getSinglePredecessor ()
getSinglePredecessor - If this basic block has a single predecessor block, return the block, otherwise return a null pointer.
Definition at line 183 of file BasicBlock.cpp.
References llvm::pred_begin(), and llvm::pred_end().
Referenced by CanPropagatePredecessorsForPHIs(), llvm::CloneAndPruneFunctionInto(), llvm::DeleteDeadBlock(), llvm::DemoteRegToStack(), llvm::DominatorTree::dominates(), FindPHIForConditionForwarding(), FoldBlockIntoPredecessor(), llvm::FoldBranchToCommonDest(), GetIfCondition(), getSinglePredecessor(), isOnlyReachableViaThisEdge(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::SplitEdge(), and TryToSimplifyUncondBranchWithICmpInIt().
const BasicBlock* llvm::BasicBlock::getSinglePredecessor () const [inline]
Definition at line 172 of file BasicBlock.h.
References getSinglePredecessor().
static iplist<Instruction> BasicBlock::* llvm::BasicBlock::getSublistAccess (Instruction *) [inline, static]
getSublistAccess() - returns pointer to member of instruction list
Definition at line 208 of file BasicBlock.h.
TerminatorInst * BasicBlock::getTerminator ()
getTerminator() - If this is a well formed basic block, then this returns a pointer to the terminator instruction. If it is not, then you get a null pointer back.
Definition at line 120 of file BasicBlock.cpp.
References llvm::iplist< NodeTy, Traits >::back(), llvm::dyn_cast(), and llvm::iplist< NodeTy, Traits >::empty().
Referenced by AddReachableCodeToWorklist(), llvm::CodeMetrics::analyzeBasicBlock(), BlockIsSimpleEnoughToThreadThrough(), canExpandBackedgeTakenCount(), llvm::CloneAndPruneFunctionInto(), llvm::CloneFunctionInto(), CloneLoopBlocks(), ConnectProlog(), llvm::ConstantFoldTerminator(), convertMemSetToLoop(), convertTransferToLoop(), createPHIsForSplitLoopExit(), llvm::DeleteDeadBlock(), DeleteInstructionInBlock(), llvm::DemotePHIToStack(), DominatesMergePoint(), FindLoopCounter(), FindMostPopularDest(), FindPHIForConditionForwarding(), FindUnconditionalPreds(), FoldBlockIntoPredecessor(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), FoldTwoEntryPHINode(), genLoopLimit(), GetBestDestForJumpOnUndef(), llvm::DOTGraphTraits< const Function * >::getEdgeSourceLabel(), getEdgeValueLocal(), llvm::Region::getExpandedRegion(), GetIfCondition(), getInsertPointForUses(), getLoopTest(), llvm::GetSuccessorNumber(), llvm::IncrementCounterInBlock(), llvm::InlineFunction(), llvm::DIBuilder::insertDeclare(), llvm::SparseSolver::isEdgeFeasible(), llvm::isInTailCallPosition(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), isSafePHIToSpeculate(), llvm::Loop::makeLoopInvariant(), MarkAliveBlocks(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), MergeEmptyReturnBlocks(), PerformHeapAllocSRoA(), removeUndefIntroducingPredecessor(), replaceSuccessorsPhiUsesWith(), llvm::UnifyFunctionExitNodes::runOnFunction(), llvm::IRBuilderBase::SetInsertPoint(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToCondBranch(), SimplifyCondBranchToTwoReturns(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), SpeculativelyExecuteBB(), splitBasicBlock(), splitBlockAndInsertIfThen(), llvm::SplitCriticalEdge(), SplitCriticalSideEffectEdges(), llvm::SplitEdge(), llvm::SplitLandingPadPredecessors(), llvm::succ_begin(), llvm::succ_end(), tryToMakeAllocaBePromotable(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopProlog(), and llvm::InstCombiner::visitCallInst().
const TerminatorInst * BasicBlock::getTerminator () const
Definition at line 125 of file BasicBlock.cpp.
References llvm::iplist< NodeTy, Traits >::back(), llvm::dyn_cast(), and llvm::iplist< NodeTy, Traits >::empty().
BasicBlock * BasicBlock::getUniquePredecessor ()
getUniquePredecessor - If this basic block has a unique predecessor block, return the block, otherwise return a null pointer. Note that unique predecessor doesn't mean single edge, there can be multiple edges from the unique predecessor to this block (for example a switch statement with multiple cases having the same destination).
Definition at line 196 of file BasicBlock.cpp.
References llvm::pred_begin(), and llvm::pred_end().
Referenced by getUniquePredecessor(), isDynamicConstant(), and llvm::MergeBlockIntoPredecessor().
const BasicBlock* llvm::BasicBlock::getUniquePredecessor () const [inline]
Definition at line 182 of file BasicBlock.h.
References getUniquePredecessor().
ValueSymbolTable * BasicBlock::getValueSymbolTable ()
getValueSymbolTable() - returns pointer to symbol table (if any)
Definition at line 27 of file BasicBlock.cpp.
References F(), and getParent().
bool llvm::BasicBlock::hasAddressTaken () const [inline]
hasAddressTaken - returns true if there are any uses of this basic block other than direct branches, switches, etc. to it.
Definition at line 258 of file BasicBlock.h.
References llvm::Value::getSubclassDataFromValue().
Referenced by llvm::CloneFunctionInto(), llvm::AsmPrinter::EmitFunctionBody(), llvm::MMIAddrLabelMap::getAddrLabelSymbol(), llvm::MMIAddrLabelMap::getAddrLabelSymbolToEmit(), hasAddressTakenAndUsed(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), llvm::UnrollLoop(), and ~BasicBlock().
bool BasicBlock::isLandingPad () const
isLandingPad - Return true if this basic block is a landing pad. I.e., it's the destination of the 'unwind' edge of an invoke instruction.
Definition at line 360 of file BasicBlock.cpp.
References getFirstNonPHI().
Referenced by ConnectProlog(), createPHIsForSplitLoopExit(), isBlockValidForExtraction(), llvm::SplitCriticalEdge(), and llvm::SplitLandingPadPredecessors().
void BasicBlock::moveAfter (BasicBlock * MovePos)
moveAfter - Unlink this basic block from its current function and insert it into the function that MovePos lives in, right after MovePos.
Definition at line 113 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), getParent(), and llvm::ARM_PROC::I.
void BasicBlock::moveBefore (BasicBlock * MovePos)
moveBefore - Unlink this basic block from its current function and insert it into the function that MovePos lives in, right before MovePos.
Definition at line 106 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), and getParent().
void BasicBlock::removeFromParent ()
removeFromParent - This method unlinks 'this' from the containing function, but does not delete it.
Definition at line 96 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), and getParent().
void BasicBlock::removePredecessor (BasicBlock * Pred, bool DontDeleteUselessPHIs = false)
removePredecessor - This method is used to notify a BasicBlock that the specified Predecessor of the block is no longer able to reach it. This is actually not used to update the Predecessor list, but is actually used to update the PHI nodes that reside in the block. Note that this should be called while the predecessor still refers to this block.
Definition at line 216 of file BasicBlock.cpp.
References begin(), llvm::dyn_cast(), llvm::iplist< NodeTy, Traits >::empty(), llvm::Instruction::eraseFromParent(), front(), llvm::UndefValue::get(), llvm::PHINode::getIncomingBlock(), getInstList(), llvm::PHINode::getNumIncomingValues(), llvm::PHINode::hasConstantValue(), llvm::Value::hasNUsesOrMore(), llvm::iplist< NodeTy, Traits >::pop_front(), llvm::pred_begin(), llvm::pred_end(), llvm::PHINode::removeIncomingValue(), and llvm::Value::replaceAllUsesWith().
Referenced by ChangeToCall(), ChangeToUnreachable(), llvm::ConstantFoldTerminator(), llvm::DeleteDeadBlock(), EliminateDeadSwitchCases(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), HandleInlinedInvoke(), llvm::RemovePredecessorAndSimplify(), removeUndefIntroducingPredecessor(), SimplifyCondBranchToTwoReturns(), SimplifyTerminatorOnSelect(), and llvm::SplitCriticalEdge().
void BasicBlock::replaceSuccessorsPhiUsesWith (BasicBlock * New)
replaceSuccessorsPhiUsesWith - Update all phi nodes in all our successors to refer to basic block New instead of to us.
Definition at line 337 of file BasicBlock.cpp.
References begin(), llvm::dyn_cast(), end(), llvm::PHINode::getBasicBlockIndex(), llvm::TerminatorInst::getNumSuccessors(), llvm::TerminatorInst::getSuccessor(), getTerminator(), llvm::ARM_PROC::IE, and llvm::PHINode::setIncomingBlock().
size_t llvm::BasicBlock::size () const [inline]
Definition at line 194 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::size().
Referenced by llvm::FastISel::FastEmitBranch(), and SimplifyBranchOnICmpChain().
BasicBlock * BasicBlock::splitBasicBlock (iterator I, const Twine & BBName = "")
splitBasicBlock - This splits a basic block into two at the specified instruction. Note that all instructions BEFORE the specified iterator stay as part of the original basic block, an unconditional branch is added to the original BB, and the rest of the instructions in the BB are moved to the new BB, including the old terminator. The newly formed BasicBlock is returned. This function invalidates the specified iterator.
Note that this only works on well formed basic blocks (must have a terminator), and 'I' must not be the end of instruction list (which would cause a degenerate basic block to be formed, having a terminator inside of the basic block).
Also note that this doesn't preserve any passes. To split blocks while keeping loop information consistent, use the SplitBlock utility function.
splitBasicBlock - This splits a basic block into two at the specified instruction. Note that all instructions BEFORE the specified iterator stay as part of the original basic block, an unconditional branch is added to the new BB, and the rest of the instructions in the BB are moved to the new BB, including the old terminator. This invalidates the iterator.
Note that this only works on well formed basic blocks (must have a terminator), and 'I' must not be the end of instruction list (which would cause a degenerate basic block to be formed, having a terminator inside of the basic block).
Definition at line 298 of file BasicBlock.cpp.
References begin(), Create(), llvm::dyn_cast(), end(), llvm::iplist< NodeTy, Traits >::end(), llvm::PHINode::getBasicBlockIndex(), getContext(), getInstList(), getParent(), getTerminator(), llvm::ARM_PROC::I, llvm::next(), llvm::PHINode::setIncomingBlock(), llvm::iplist< NodeTy, Traits >::splice(), llvm::succ_begin(), and llvm::succ_end().
Referenced by convertMemSetToLoop(), convertTransferToLoop(), HandleCallsInBlockInlinedThroughInvoke(), llvm::InlineFunction(), PerformHeapAllocSRoA(), llvm::NVPTXSplitBBatBar::runOnFunction(), SimplifyBranchOnICmpChain(), llvm::SplitBlock(), and splitBlockAndInsertIfThen().
Friends And Related Function Documentation
friend class BlockAddress [friend]
Definition at line 72 of file BasicBlock.h.
friend class SymbolTableListTraits< BasicBlock, Function > [friend]
Definition at line 80 of file BasicBlock.h.
The documentation for this class was generated from the following files:
BasicBlock.h
BasicBlock.cpp