LLVM: llvm::DenseSet< ValueT, ValueInfoT > Class Template Reference
LLVM API Documentation
llvm::DenseSet< ValueT, ValueInfoT > Class Template Reference
#include <DenseSet.h>
Classes
class ConstIterator
class Iterator
Public Types
typedef Iterator iterator
typedef ConstIterator const_iterator
Public Member Functions
DenseSet (const DenseSet &Other)
DenseSet (unsigned NumInitBuckets=0)
bool empty () const
unsigned size () const
void resize (size_t Size)
Grow the denseset so that it has at least Size buckets. Does not shrink.
void clear ()
bool count (const ValueT &V) const
bool erase (const ValueT &V)
void swap (DenseSet &RHS)
DenseSet & operator= (const DenseSet &RHS)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
iterator find (const ValueT &V)
void erase (Iterator I)
void erase (ConstIterator CI)
std::pair< iterator, bool > insert (const ValueT &V)
template<typename InputIt >
void insert (InputIt I, InputIt E)
Detailed Description
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>>
class llvm::DenseSet< ValueT, ValueInfoT >
DenseSet - This implements a dense probed hash-table based set.
FIXME: This is currently implemented directly in terms of DenseMap, this should be optimized later if there is a need.
Definition at line 26 of file DenseSet.h.
Member Typedef Documentation
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef ConstIterator llvm::DenseSet< ValueT, ValueInfoT >::const_iterator
Definition at line 103 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef Iterator llvm::DenseSet< ValueT, ValueInfoT >::iterator
Definition at line 102 of file DenseSet.h.
Constructor & Destructor Documentation
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> llvm::DenseSet< ValueT, ValueInfoT >::DenseSet (const DenseSet< ValueT, ValueInfoT > & Other) [inline]
Definition at line 30 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> llvm::DenseSet< ValueT, ValueInfoT >::DenseSet (unsigned NumInitBuckets = 0) [inline, explicit]
Definition at line 31 of file DenseSet.h.
Member Function Documentation
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> iterator llvm::DenseSet< ValueT, ValueInfoT >::begin () [inline]
Definition at line 105 of file DenseSet.h.
Referenced by llvm::X86COFFMachineModuleInfo::externals_begin(), llvm::LiveIntervals::HMEditor::moveAllRangesFrom(), llvm::LiveIntervals::HMEditor::moveAllRangesInto(), and llvm::MachineConstantPool::~MachineConstantPool().
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> const_iterator llvm::DenseSet< ValueT, ValueInfoT >::begin () const [inline]
Definition at line 108 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> void llvm::DenseSet< ValueT, ValueInfoT >::clear () [inline]
Definition at line 39 of file DenseSet.h.
Referenced by llvm::LiveIntervals::HMEditor::moveAllRangesInto().
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> bool llvm::DenseSet< ValueT, ValueInfoT >::count (const ValueT & V) const [inline]
Definition at line 43 of file DenseSet.h.
Referenced by llvm::LoopInfo::verifyAnalysis().
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> bool llvm::DenseSet< ValueT, ValueInfoT >::empty () const [inline]
Definition at line 33 of file DenseSet.h.
Referenced by llvm::ScalarEvolution::releaseMemory().
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> iterator llvm::DenseSet< ValueT, ValueInfoT >::end () [inline]
Definition at line 106 of file DenseSet.h.
Referenced by llvm::X86COFFMachineModuleInfo::externals_end(), llvm::LiveIntervals::HMEditor::moveAllRangesFrom(), llvm::LiveIntervals::HMEditor::moveAllRangesInto(), and llvm::MachineConstantPool::~MachineConstantPool().
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> const_iterator llvm::DenseSet< ValueT, ValueInfoT >::end () const [inline]
Definition at line 109 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> bool llvm::DenseSet< ValueT, ValueInfoT >::erase (const ValueT & V) [inline]
Definition at line 47 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> void llvm::DenseSet< ValueT, ValueInfoT >::erase (Iterator I) [inline]
Definition at line 112 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> void llvm::DenseSet< ValueT, ValueInfoT >::erase (ConstIterator CI) [inline]
Definition at line 113 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> iterator llvm::DenseSet< ValueT, ValueInfoT >::find (const ValueT & V) [inline]
Definition at line 111 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> std::pair<iterator, bool> llvm::DenseSet< ValueT, ValueInfoT >::insert (const ValueT & V) [inline]
Definition at line 115 of file DenseSet.h.
Referenced by llvm::X86COFFMachineModuleInfo::addExternalFunction(), llvm::MachineConstantPool::getConstantPoolIndex(), getRegsUsedByPHIs(), llvm::DenseSet< MCSymbol const * >::insert(), and llvm::LoopBase< BlockT, LoopT >::verifyLoopNest().
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> template<typename InputIt > void llvm::DenseSet< ValueT, ValueInfoT >::insert (InputIt I, InputIt E) [inline]
Definition at line 121 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> DenseSet& llvm::DenseSet< ValueT, ValueInfoT >::operator= (const DenseSet< ValueT, ValueInfoT > & RHS) [inline]
Definition at line 55 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> void llvm::DenseSet< ValueT, ValueInfoT >::resize (size_t Size) [inline]
Grow the denseset so that it has at least Size buckets. Does not shrink.
Definition at line 37 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> unsigned llvm::DenseSet< ValueT, ValueInfoT >::size () const [inline]
Definition at line 34 of file DenseSet.h.
Referenced by llvm::LiveIntervals::HMEditor::moveAllRangesInto().
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> void llvm::DenseSet< ValueT, ValueInfoT >::swap (DenseSet< ValueT, ValueInfoT > & RHS) [inline]
Definition at line 51 of file DenseSet.h.
The documentation for this class was generated from the following file:
DenseSet.h