LLVM: llvm::Instruction Class Reference
LLVM API Documentation
llvm::Instruction Class Reference
#include <Instruction.h>
Public Types
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0, CompareUsingScalarTypes = 1<<1 }
enum TermOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum OtherOps
Public Member Functions
~Instruction ()
Instruction * use_back ()
const Instruction * use_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
void removeFromParent ()
void eraseFromParent ()
void insertBefore (Instruction *InsertPos)
void insertAfter (Instruction *InsertPos)
void moveBefore (Instruction *MovePos)
unsigned getOpcode () const
getOpcode() returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isBinaryOp () const
bool isShift ()
bool isCast () const
bool isLogicalShift () const
bool isArithmeticShift () const
isArithmeticShift - Return true if this is an arithmetic shift right.
bool hasMetadata () const
bool hasMetadataOtherThanDebugLoc () const
MDNode * getMetadata (unsigned KindID) const
MDNode * getMetadata (StringRef Kind) const
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void setMetadata (unsigned KindID, MDNode *Node)
void setMetadata (StringRef Kind, MDNode *Node)
void setDebugLoc (const DebugLoc &Loc)
setDebugLoc - Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
getDebugLoc - Return the debug location for this node as a DebugLoc.
bool isAssociative () const
bool isCommutative () const
bool isIdempotent () const
bool isNilpotent () const
bool mayWriteToMemory () const
bool mayReadFromMemory () const
bool mayReadOrWriteMemory () const
bool mayThrow () const
bool mayHaveSideEffects () const
Instruction * clone () const
bool isIdenticalTo (const Instruction *I) const
bool isIdenticalToWhenDefined (const Instruction *I) const
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
Determine if one instruction is the same operation as another.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Static Public Member Functions
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isBinaryOp (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isAssociative (unsigned op)
static bool isCommutative (unsigned op)
static bool isIdempotent (unsigned op)
static bool isNilpotent (unsigned op)
static bool classof (const Instruction *)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
Protected Member Functions
void setInstructionSubclassData (unsigned short D)
unsigned getSubclassDataFromInstruction () const
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=0)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
virtual Instruction * clone_impl () const =0
Friends
class SymbolTableListTraits< Instruction, BasicBlock >
Detailed Description
Definition at line 30 of file Instruction.h.
Member Enumeration Documentation
enum llvm::Instruction::BinaryOps
Definition at line 328 of file Instruction.h.
enum llvm::Instruction::CastOps
Definition at line 342 of file Instruction.h.
enum llvm::Instruction::MemoryOps
Definition at line 335 of file Instruction.h.
enum llvm::Instruction::OperationEquivalenceFlags
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
Enumerator:
CompareIgnoringAlignment
Check for equivalence ignoring load/store alignment.
CompareUsingScalarTypes
Check for equivalence treating a type and a vector of that type as equivalent.
Definition at line 287 of file Instruction.h.
enum llvm::Instruction::OtherOps
Definition at line 349 of file Instruction.h.
enum llvm::Instruction::TermOps
Definition at line 321 of file Instruction.h.
Constructor & Destructor Documentation
Instruction::~Instruction ()
Definition at line 50 of file Instruction.cpp.
Instruction::Instruction (Type * Ty, unsigned iType, Use * Ops, unsigned NumOps, Instruction * InsertBefore = 0) [protected]
Definition at line 23 of file Instruction.cpp.
References llvm::LeakDetector::addGarbageObject(), llvm::BasicBlock::getInstList(), and getParent().
Instruction::Instruction (Type * Ty, unsigned iType, Use * Ops, unsigned NumOps, BasicBlock * InsertAtEnd) [protected]
Definition at line 37 of file Instruction.cpp.
References llvm::LeakDetector::addGarbageObject(), and llvm::BasicBlock::getInstList().
Member Function Documentation
static bool llvm::Instruction::classof (const Instruction *) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented in llvm::BitCastInst, llvm::PtrToIntInst, llvm::IntToPtrInst, llvm::FPToSIInst, llvm::FPToUIInst, llvm::SIToFPInst, llvm::UIToFPInst, llvm::FPExtInst, llvm::FPTruncInst, llvm::SExtInst, llvm::ZExtInst, llvm::TruncInst, llvm::UnreachableInst, llvm::ResumeInst, llvm::InvokeInst, llvm::IndirectBrInst, llvm::SwitchInst, llvm::BranchInst, llvm::ReturnInst, llvm::LandingPadInst, llvm::PHINode, llvm::InsertValueInst, llvm::ExtractValueInst, llvm::ShuffleVectorInst, llvm::InsertElementInst, llvm::ExtractElementInst, llvm::VAArgInst, llvm::SelectInst, llvm::CallInst, llvm::FCmpInst, llvm::ICmpInst, llvm::GetElementPtrInst, llvm::CmpInst, llvm::AtomicRMWInst, llvm::CastInst, llvm::AtomicCmpXchgInst, llvm::FenceInst, llvm::BinaryOperator, llvm::StoreInst, llvm::LoadInst, llvm::UnaryInstruction, llvm::AllocaInst, and llvm::TerminatorInst.
Definition at line 313 of file Instruction.h.
static bool llvm::Instruction::classof (const Value * V) [inline, static]
Reimplemented from llvm::User.
Reimplemented in llvm::BitCastInst, llvm::PtrToIntInst, llvm::IntToPtrInst, llvm::FPToSIInst, llvm::FPToUIInst, llvm::SIToFPInst, llvm::UIToFPInst, llvm::FPExtInst, llvm::FPTruncInst, llvm::SExtInst, llvm::ZExtInst, llvm::TruncInst, llvm::UnreachableInst, llvm::ResumeInst, llvm::InvokeInst, llvm::IndirectBrInst, llvm::SwitchInst, llvm::BranchInst, llvm::ReturnInst, llvm::LandingPadInst, llvm::PHINode, llvm::InsertValueInst, llvm::ExtractValueInst, llvm::ShuffleVectorInst, llvm::InsertElementInst, llvm::ExtractElementInst, llvm::VAArgInst, llvm::SelectInst, llvm::CallInst, llvm::FCmpInst, llvm::ICmpInst, llvm::GetElementPtrInst, llvm::CmpInst, llvm::AtomicRMWInst, llvm::CastInst, llvm::AtomicCmpXchgInst, llvm::FenceInst, llvm::BinaryOperator, llvm::StoreInst, llvm::MemMoveInst, llvm::MemCpyInst, llvm::MemTransferInst, llvm::LoadInst, llvm::MemSetInst, llvm::MemIntrinsic, llvm::UnaryInstruction, llvm::AllocaInst, llvm::DbgValueInst, llvm::DbgDeclareInst, llvm::TerminatorInst, llvm::DbgInfoIntrinsic, and llvm::IntrinsicInst.
Definition at line 314 of file Instruction.h.
References llvm::Value::getValueID(), and llvm::Value::InstructionVal.
Instruction * Instruction::clone () const
clone() - Create a copy of 'this' instruction that is identical in all ways except the following: The instruction has no parent The instruction has no name
Definition at line 432 of file Instruction.cpp.
References clone_impl(), getAllMetadataOtherThanDebugLoc(), getDebugLoc(), hasMetadata(), setDebugLoc(), setMetadata(), llvm::SmallVectorTemplateCommon< T >::size(), and llvm::Value::SubclassOptionalData.
Referenced by llvm::CloneBasicBlock(), llvm::FoldBranchToCommonDest(), llvm::FoldReturnIntoUncondBranch(), HoistThenElseCodeToIf(), and llvm::SplitLandingPadPredecessors().
virtual Instruction* llvm::Instruction::clone_impl () const [protected, pure virtual]
Implemented in llvm::BitCastInst, llvm::PtrToIntInst, llvm::IntToPtrInst, llvm::FPToSIInst, llvm::FPToUIInst, llvm::SIToFPInst, llvm::UIToFPInst, llvm::FPExtInst, llvm::FPTruncInst, llvm::SExtInst, llvm::ZExtInst, llvm::TruncInst, llvm::UnreachableInst, llvm::ResumeInst, llvm::InvokeInst, llvm::IndirectBrInst, llvm::SwitchInst, llvm::BranchInst, llvm::ReturnInst, llvm::LandingPadInst, llvm::PHINode, llvm::InsertValueInst, llvm::ExtractValueInst, llvm::ShuffleVectorInst, llvm::InsertElementInst, llvm::ExtractElementInst, llvm::VAArgInst, llvm::SelectInst, llvm::CallInst, llvm::FCmpInst, llvm::ICmpInst, llvm::GetElementPtrInst, llvm::AtomicRMWInst, llvm::AtomicCmpXchgInst, llvm::FenceInst, llvm::StoreInst, llvm::BinaryOperator, llvm::LoadInst, llvm::AllocaInst, and llvm::TerminatorInst.
Referenced by clone().
void Instruction::eraseFromParent ()
eraseFromParent - This method unlinks 'this' from the containing basic block and deletes it.
Definition at line 71 of file Instruction.cpp.
References llvm::BasicBlock::getInstList(), and getParent().
Referenced by AddReachableCodeToWorklist(), BuildSubAggregate(), ChangeToCall(), checkCSEInPredecessor(), llvm::CloneAndPruneFunctionInto(), CloneLoopBlocks(), ConnectProlog(), llvm::ConstantFoldTerminator(), DeleteDeadInstruction(), deleteDeadInstruction(), DeleteTriviallyDeadInstructions(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::InstCombiner::DoOneIteration(), llvm::EliminateDuplicatePHINodes(), llvm::InstCombiner::EraseInstFromFunction(), EraseInstruction(), EraseTerminatorInstAndDCECond(), FindPHIToPartitionLoops(), llvm::FoldReturnIntoUncondBranch(), FoldTwoEntryPHINode(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), InlineCallIfPossible(), llvm::InlineFunction(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), llvm::LowerDbgDeclare(), LowerFenceInst(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::IntrinsicLowering::LowerToByteSwap(), MarkAliveBlocks(), llvm::BitcodeReader::MaterializeModule(), llvm::MergeBasicBlockIntoOnlyPred(), MergeEmptyReturnBlocks(), OptimizeCmpExpression(), OptimizeGlobalAddressOfMalloc(), OptimizeNoopCopyExpression(), PerformHeapAllocSRoA(), llvm::PHITransAddr::PHITranslateWithInsertion(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::PHINode::removeIncomingValue(), removeLifetimeIntrinsicUsers(), llvm::BasicBlock::removePredecessor(), removeUndefIntroducingPredecessor(), replaceAndRecursivelySimplifyImpl(), ReplaceUsesOfMallocWithGlobal(), ReplaceUsesOfWith(), RewriteUsesOfLoadForHeapSRoA(), llvm::LoadAndStorePromoter::run(), llvm::NVPTXLowerAggrCopies::runOnFunction(), llvm::Inliner::runOnSCC(), SimplifyBranchOnICmpChain(), llvm::SplitLandingPadPredecessors(), StripDebugInfo(), tryToMakeAllocaBePromotable(), TryToOptimizeStoreOfMallocToGlobal(), TryToShrinkGlobalToBoolean(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSimplifyUncondBranchWithICmpInIt(), TurnSwitchRangeIntoICmp(), llvm::UnrollLoop(), llvm::UpgradeIntrinsicCall(), and llvm::ObjectSizeOffsetEvaluator::visitPHINode().
void llvm::Instruction::getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > & MDs) const [inline]
getAllMetadata - Get all metadata attached to this Instruction. The first element of each pair returned is the KindID, the second element is the metadata value. This list is returned sorted by the KindID.
Definition at line 154 of file Instruction.h.
References hasMetadata().
Referenced by llvm::RemapInstruction().
void llvm::Instruction::getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > & MDs) const [inline]
getAllMetadataOtherThanDebugLoc - This does the same thing as getAllMetadata, except that it filters out the debug location.
Definition at line 161 of file Instruction.h.
References hasMetadataOtherThanDebugLoc().
Referenced by clone().
const DebugLoc& llvm::Instruction::getDebugLoc () const [inline]
getDebugLoc - Return the debug location for this node as a DebugLoc.
Definition at line 177 of file Instruction.h.
Referenced by BreakUpSubtract(), ChangeToCall(), ChangeToUnreachable(), clone(), llvm::ConvertDebugDeclareToDebugValue(), ConvertShiftToMul(), llvm::InstCombiner::DoOneIteration(), fixupLineNumbers(), GetLoadValueForLoad(), llvm::InstCombiner::InsertNewInstWith(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), LowerNegateToMultiply(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::FastISel::SelectInstruction(), llvm::FastISel::SelectOperator(), llvm::FunctionLoweringInfo::set(), llvm::IRBuilderBase::SetInsertPoint(), SimplifyTerminatorOnSelect(), llvm::SplitCriticalEdge(), TryToSimplifyUncondBranchWithICmpInIt(), and llvm::SelectionDAGBuilder::visit().
MDNode* llvm::Instruction::getMetadata (unsigned KindID) const [inline]
getMetadata - Get the metadata of given kind attached to this Instruction. If the metadata is not found then return null.
Definition at line 139 of file Instruction.h.
References hasMetadata().
Referenced by llvm::AliasSetTracker::add(), ComputePostOrders(), llvm::LLVMContext::emitError(), ExtractBranchMetadata(), llvm::getAlign(), llvm::AliasAnalysis::getLocation(), llvm::AliasAnalysis::getLocationForDest(), llvm::AliasAnalysis::getLocationForSource(), llvm::AliasAnalysis::getModRefInfo(), isVtableAccess(), patchReplacementInstruction(), llvm::AliasSetTracker::remove(), llvm::BranchInst::swapSuccessors(), and tryToMakeAllocaBePromotable().
MDNode* llvm::Instruction::getMetadata (StringRef Kind) const [inline]
getMetadata - Get the metadata of given kind attached to this Instruction. If the metadata is not found then return null.
Definition at line 146 of file Instruction.h.
References hasMetadata().
unsigned llvm::Instruction::getOpcode () const [inline]
getOpcode() returns a member of one of the enums like Instruction::Add.
Reimplemented in llvm::SelectInst, llvm::CmpInst, llvm::CastInst, and llvm::BinaryOperator.
Definition at line 82 of file Instruction.h.
References llvm::Value::getValueID(), and llvm::Value::InstructionVal.
Referenced by CanEvaluateSExtd(), CanEvaluateShifted(), CanEvaluateTruncated(), CanEvaluateZExtd(), CanPHITrans(), CheapToScalarize(), llvm::OverflowingBinaryOperator::classof(), llvm::AllocaInst::classof(), llvm::UnaryInstruction::classof(), llvm::PossiblyExactOperator::classof(), llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Mul >::classof(), llvm::LoadInst::classof(), llvm::StoreInst::classof(), llvm::FenceInst::classof(), llvm::AtomicCmpXchgInst::classof(), llvm::AtomicRMWInst::classof(), llvm::CmpInst::classof(), llvm::GetElementPtrInst::classof(), llvm::ICmpInst::classof(), llvm::FCmpInst::classof(), llvm::CallInst::classof(), llvm::SelectInst::classof(), llvm::VAArgInst::classof(), llvm::ExtractElementInst::classof(), llvm::InsertElementInst::classof(), llvm::ShuffleVectorInst::classof(), llvm::ExtractValueInst::classof(), llvm::InsertValueInst::classof(), llvm::PHINode::classof(), llvm::LandingPadInst::classof(), llvm::ReturnInst::classof(), llvm::BranchInst::classof(), llvm::SwitchInst::classof(), llvm::IndirectBrInst::classof(), llvm::InvokeInst::classof(), llvm::ResumeInst::classof(), llvm::UnreachableInst::classof(), llvm::TruncInst::classof(), llvm::ZExtInst::classof(), llvm::SExtInst::classof(), llvm::FPTruncInst::classof(), llvm::FPExtInst::classof(), llvm::UIToFPInst::classof(), llvm::SIToFPInst::classof(), llvm::FPToUIInst::classof(), llvm::FPToSIInst::classof(), llvm::IntToPtrInst::classof(), llvm::PtrToIntInst::classof(), llvm::BitCastInst::classof(), CollectBSwapParts(), collectFailStats(), CollectInsertionElements(), llvm::ConstantFoldInstruction(), dyn_castFoldableMul(), EvaluateExpression(), llvm::SelectionDAGBuilder::FindMergedConditions(), FoldOperationIntoSelectOperand(), llvm::InstCombiner::FoldSelectOpOp(), GatherConstantCompares(), llvm::SCEVExpander::getIVIncOperand(), getLoopPhiForCounter(), llvm::AliasAnalysis::getModRefInfo(), llvm::CastInst::getOpcode(), llvm::SelectInst::getOpcode(), getOpcodeName(), GetSelectFoldableConstant(), GetSelectFoldableOperands(), GetShiftedValue(), llvm::InlineFunction(), isAllocSiteRemovable(), isArithmeticShift(), isAssociative(), isBinaryOp(), isCast(), isCommutative(), isHighCostExpansion(), isIdempotent(), isIdenticalToWhenDefined(), isLogicalShift(), isNilpotent(), isSameOperationAs(), isShift(), isTerminator(), isUnmovableInstruction(), LookThroughFPExtensions(), mayReadFromMemory(), mayWriteToMemory(), MightBeFoldableInst(), llvm::PointerMayBeCaptured(), PrintOps(), llvm::FastISel::SelectInstruction(), SimplifyBranchOnICmpChain(), llvm::SimplifyInstruction(), SimplifyWithOpReplaced(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), ThreadBinOpOverSelect(), llvm::SelectionDAGBuilder::visit(), llvm::Interpreter::visitAllocaInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitSwitchInst(), and WriteInstruction().
const char* llvm::Instruction::getOpcodeName () const [inline]
Definition at line 84 of file Instruction.h.
References getOpcode(), and getOpcodeName().
Referenced by getOpcodeName(), and PrintOps().
const char * Instruction::getOpcodeName (unsigned OpCode) [static]
Definition at line 96 of file Instruction.cpp.
References llvm::Alloca, llvm::APIntOps::And(), llvm::Call, llvm::ExtractElement, llvm::FPExt, llvm::FPToSI, llvm::ICmp, llvm::InsertValue, llvm::IntToPtr, llvm::SPII::Load, llvm::LShr, llvm::APIntOps::Or(), llvm::PHI, llvm::MBlazeISD::Ret, llvm::Select, llvm::SExt, llvm::ShuffleVector, llvm::SIToFP, llvm::SPII::Store, llvm::Trunc, and llvm::APIntOps::Xor().
const BasicBlock* llvm::Instruction::getParent () const [inline]
Definition at line 51 of file Instruction.h.
Referenced by llvm::IVUsers::AddUsersImpl(), BlockIsSimpleEnoughToThreadThrough(), canConstantEvolve(), llvm::AliasAnalysis::canInstructionRangeModify(), CanSelectOperandBeMappingIntoPredBlock(), ChangeToCall(), ChangeToUnreachable(), llvm::CloneAndPruneFunctionInto(), ConstructSSAForLoadSet(), llvm::Region::contains(), convertMemSetToLoop(), convertTransferToLoop(), createFree(), createMalloc(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::DominatorTree::dominates(), DominatesMergePoint(), llvm::InstCombiner::DoOneIteration(), llvm::Value::DoPHITranslation(), EliminateDeadSwitchCases(), eraseFromParent(), llvm::SCEVExpander::expandCodeFor(), FindInitTrampolineFromBB(), llvm::SelectionDAGBuilder::FindMergedConditions(), FindPhiPredForUseInBlock(), llvm::SimplifyFortifiedLibCalls::fold(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), FoldTwoEntryPHINode(), getCommonReturnValue(), llvm::MemoryDependenceAnalysis::getDependency(), getInsertPointForUses(), llvm::MemoryDependenceAnalysis::getLoadLoadClobberFullWidthSize(), GetLoadValueForLoad(), getLoopPhiForCounter(), GetMemInstValueForLoad(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), GetStoreValueForLoad(), HandleByValArgument(), HandleInlinedInvoke(), llvm::SCEVExpander::hoistIVInc(), HoistThenElseCodeToIf(), InBlock(), InlineCallIfPossible(), llvm::InlineFunction(), insertAfter(), insertBefore(), llvm::InstCombiner::InsertNewInstBefore(), Instruction(), isDynamicConstant(), llvm::isInTailCallPosition(), isInteresting(), isLoopInvariant(), isProfitableToFoldUnconditional(), llvm::DominatorTree::isReachableFromEntry(), isSafeAndProfitableToSinkLoad(), isSafePHIToSpeculate(), llvm::isSafeToLoadUnconditionally(), llvm::AllocaInst::isStaticAlloca(), llvm::Value::isUsedInBasicBlock(), isUsedOutsideOfDefiningBlock(), IVUseShouldUsePostIncValue(), LLVMGetNextInstruction(), LLVMGetPreviousInstruction(), LLVMPositionBuilderBefore(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), LowerBSWAP(), LowerCTLZ(), LowerCTPOP(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::IntrinsicLowering::LowerToByteSwap(), moveBefore(), NegateValue(), OptimizeCmpExpression(), OptimizeNoopCopyExpression(), passingValueIsAlwaysUndefined(), PerformHeapAllocSRoA(), llvm::PHITransAddr::PHITranslateValue(), llvm::Value::print(), PrintOps(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), llvm::SSAUpdaterImpl< UpdaterT >::RecordMatchingPHIs(), removeFromParent(), replaceAndRecursivelySimplifyImpl(), ReplaceCallWith(), llvm::ReplaceInstWithInst(), llvm::LoopInfo::replacementPreservesLCSSAForm(), llvm::SSAUpdater::RewriteUse(), llvm::SSAUpdater::RewriteUseAfterInsertions(), RewriteUsesOfClonedInstructions(), llvm::LoadAndStorePromoter::run(), llvm::NVPTXSplitBBatBar::runOnFunction(), SafeToMergeTerminators(), llvm::FastISel::SelectInstruction(), llvm::IRBuilderBase::SetInsertPoint(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToCondBranch(), SimplifyCondBranchToTwoReturns(), llvm::InstCombiner::SimplifyDivRemOfSelect(), SimplifyTerminatorOnSelect(), llvm::simplifyUsersOfIV(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), llvm::SparseSolver::Solve(), SpeculativelyExecuteBB(), splitBlockAndInsertIfThen(), llvm::SplitCriticalEdge(), TryToSimplifyUncondBranchWithICmpInIt(), TryToSinkInstruction(), TurnSwitchRangeIntoICmp(), UpdateCallGraphAfterInlining(), llvm::UpgradeIntrinsicCall(), ValueDominatesPHI(), llvm::SelectionDAGBuilder::visit(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitCallInst(), llvm::Interpreter::visitCallSite(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFPTrunc(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitPHINode(), and llvm::InstCombiner::visitStoreInst().
BasicBlock* llvm::Instruction::getParent () [inline]
Definition at line 52 of file Instruction.h.
unsigned llvm::Instruction::getSubclassDataFromInstruction () const [inline, protected]
Definition at line 382 of file Instruction.h.
Referenced by llvm::AllocaInst::getAlignment(), llvm::LoadInst::getAlignment(), llvm::StoreInst::getAlignment(), llvm::CallInst::getCallingConv(), llvm::LoadInst::getOrdering(), llvm::StoreInst::getOrdering(), llvm::AtomicCmpXchgInst::getOrdering(), llvm::CmpInst::getPredicate(), llvm::LoadInst::getSynchScope(), llvm::StoreInst::getSynchScope(), llvm::AtomicCmpXchgInst::getSynchScope(), llvm::CallInst::isTailCall(), llvm::LoadInst::isVolatile(), llvm::StoreInst::isVolatile(), llvm::AtomicCmpXchgInst::isVolatile(), llvm::LoadInst::setAlignment(), llvm::StoreInst::setAlignment(), llvm::CallInst::setCallingConv(), llvm::LoadInst::setOrdering(), llvm::StoreInst::setOrdering(), llvm::AtomicCmpXchgInst::setOrdering(), llvm::LoadInst::setSynchScope(), llvm::StoreInst::setSynchScope(), llvm::AtomicCmpXchgInst::setSynchScope(), llvm::CallInst::setTailCall(), llvm::LoadInst::setVolatile(), llvm::StoreInst::setVolatile(), and llvm::AtomicCmpXchgInst::setVolatile().
bool llvm::Instruction::hasMetadata () const [inline]
hasMetadata() - Return true if this instruction has any metadata attached to it.
Definition at line 127 of file Instruction.h.
References llvm::DebugLoc::isUnknown().
Referenced by clone(), getAllMetadata(), getMetadata(), and setMetadata().
bool llvm::Instruction::hasMetadataOtherThanDebugLoc () const [inline]
hasMetadataOtherThanDebugLoc - Return true if this instruction has metadata attached to it other than a debug location.
Definition at line 133 of file Instruction.h.
Referenced by getAllMetadataOtherThanDebugLoc().
void Instruction::insertAfter (Instruction * InsertPos)
insertAfter - Insert an unlinked instructions into a basic block immediately after the specified instruction.
Definition at line 83 of file Instruction.cpp.
References llvm::BasicBlock::getInstList(), and getParent().
void Instruction::insertBefore (Instruction * InsertPos)
insertBefore - Insert an unlinked instructions into a basic block immediately before the specified instruction.
Definition at line 77 of file Instruction.cpp.
References llvm::BasicBlock::getInstList(), and getParent().
Referenced by llvm::UnrollRuntimeLoopProlog().
bool llvm::Instruction::isArithmeticShift () const [inline]
isArithmeticShift - Return true if this is an arithmetic shift right.
Definition at line 112 of file Instruction.h.
References getOpcode().
Referenced by llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
bool llvm::Instruction::isAssociative () const [inline]
isAssociative - Return true if the instruction is associative:
Associative operators satisfy: x op (y op z) === (x op y) op z
In LLVM, the Add, Mul, And, Or, and Xor operators are associative.
Definition at line 205 of file Instruction.h.
References getOpcode(), and isAssociative().
Referenced by llvm::ConstantFoldBinaryInstruction(), isAssociative(), LinearizeExprTree(), SimplifyAssociativeBinOp(), and SimplifyBinOp().
bool Instruction::isAssociative (unsigned Opcode) [static]
isAssociative - Return true if the instruction is associative:
Associative operators satisfy: x op (y op z) === (x op y) op z
In LLVM, the Add, Mul, And, Or, and Xor operators are associative.
Definition at line 382 of file Instruction.cpp.
References llvm::APIntOps::And(), llvm::APIntOps::Or(), and llvm::APIntOps::Xor().
bool llvm::Instruction::isBinaryOp () const [inline]
Definition at line 86 of file Instruction.h.
References getOpcode(), and isBinaryOp().
Referenced by llvm::ConstantFoldInstOperands(), and isBinaryOp().
static bool llvm::Instruction::isBinaryOp (unsigned Opcode) [inline, static]
Definition at line 96 of file Instruction.h.
bool llvm::Instruction::isCast () const [inline]
Definition at line 88 of file Instruction.h.
References getOpcode(), and isCast().
Referenced by llvm::CastInst::classof(), llvm::ConstantCreator< ConstantExpr, Type, ExprMapKeyType >::create(), foldConstantCastPair(), llvm::InstCombiner::FoldSelectOpOp(), llvm::ConstantExpr::getCast(), isCast(), WriteConstants(), and WriteInstruction().
static bool llvm::Instruction::isCast (unsigned OpCode) [inline, static]
Determine if the OpCode is one of the CastInst instructions.
Definition at line 117 of file Instruction.h.
bool llvm::Instruction::isCommutative () const [inline]
isCommutative - Return true if the instruction is commutative:
Commutative operators satisfy: (x op y) === (y op x)
In LLVM, these are the associative operators, plus SetEQ and SetNE, when applied to any type.
Reimplemented in llvm::FCmpInst, llvm::ICmpInst, and llvm::CmpInst.
Definition at line 215 of file Instruction.h.
References getOpcode(), and isCommutative().
Referenced by llvm::ConstantFoldBinaryInstruction(), ExpandBinOp(), FactorizeBinOp(), llvm::InstCombiner::FoldSelectOpOp(), isCommutative(), LinearizeExprTree(), RightDistributesOverLeft(), SimplifyAssociativeBinOp(), llvm::BinaryOperator::swapOperands(), and ThreadBinOpOverSelect().
bool Instruction::isCommutative (unsigned op) [static]
isCommutative - Return true if the instruction is commutative:
Commutative operators satisfy: (x op y) === (y op x)
In LLVM, these are the associative operators, plus SetEQ and SetNE, when applied to any type.
Definition at line 394 of file Instruction.cpp.
References llvm::APIntOps::And(), llvm::APIntOps::Or(), and llvm::APIntOps::Xor().
bool llvm::Instruction::isIdempotent () const [inline]
isIdempotent - Return true if the instruction is idempotent:
Idempotent operators satisfy: x op x === x
In LLVM, the And and Or operators are idempotent.
Definition at line 224 of file Instruction.h.
References getOpcode(), and isIdempotent().
Referenced by IncorporateWeight(), and isIdempotent().
bool Instruction::isIdempotent (unsigned Opcode) [static]
isIdempotent - Return true if the instruction is idempotent:
Idempotent operators satisfy: x op x === x
In LLVM, the And and Or operators are idempotent.
Definition at line 415 of file Instruction.cpp.
References llvm::APIntOps::And(), and llvm::APIntOps::Or().
bool Instruction::isIdenticalTo (const Instruction * I) const
isIdenticalTo - Return true if the specified instruction is exactly identical to the current one. This means that all operands match and any extra information (e.g. load is volatile) agree.
Definition at line 173 of file Instruction.cpp.
References isIdenticalToWhenDefined(), and llvm::Value::SubclassOptionalData.
Referenced by checkCSEInPredecessor().
bool Instruction::isIdenticalToWhenDefined (const Instruction * I) const
isIdenticalToWhenDefined - This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which specify conditions under which the instruction's result is undefined.
Definition at line 181 of file Instruction.cpp.
References llvm::Intrinsic::getAttributes(), llvm::PHINode::getIncomingBlock(), llvm::User::getNumOperands(), getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::ARM_PROC::I, and LI.
Referenced by HoistThenElseCodeToIf(), and isIdenticalTo().
bool llvm::Instruction::isLogicalShift () const [inline]
isLogicalShift - Return true if this is a logical shift left or a logical shift right.
Definition at line 107 of file Instruction.h.
References getOpcode(), and llvm::LShr.
Referenced by CollectBSwapParts(), llvm::InstCombiner::FoldShiftByConstant(), and llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
bool llvm::Instruction::isNilpotent () const [inline]
isNilpotent - Return true if the instruction is nilpotent:
Nilpotent operators satisfy: x op x === Id,
where Id is the identity for the operator, i.e. a constant such that x op Id === x and Id op x === x for all x.
In LLVM, the Xor operator is nilpotent.
Definition at line 236 of file Instruction.h.
References getOpcode(), and isNilpotent().
Referenced by IncorporateWeight(), and isNilpotent().
bool Instruction::isNilpotent (unsigned Opcode) [static]
isNilpotent - Return true if the instruction is nilpotent:
Nilpotent operators satisfy: x op x === Id,
where Id is the identity for the operator, i.e. a constant such that x op Id === x and Id op x === x for all x.
In LLVM, the Xor operator is nilpotent.
Definition at line 428 of file Instruction.cpp.
References llvm::APIntOps::Xor().
bool Instruction::isSameOperationAs (const Instruction * I, unsigned flags = 0) const
Determine if one instruction is the same operation as another.
This function determines if the specified instruction executes the same operation as the current one. This means that the opcodes, type, operand types and any other factors affecting the operation must be the same. This is similar to isIdenticalTo except the operands themselves don't have to be identical.
Returns:
true if the specified instruction is the same operation as the current one.
Definition at line 243 of file Instruction.cpp.
References CompareIgnoringAlignment, CompareUsingScalarTypes, llvm::Intrinsic::getAttributes(), llvm::User::getNumOperands(), getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::ARM_PROC::I, and LI.
bool llvm::Instruction::isShift () [inline]
Definition at line 87 of file Instruction.h.
References getOpcode(), and isShift().
Referenced by llvm::InstCombiner::FoldShiftByConstant(), isShift(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), and llvm::InstCombiner::visitXor().
static bool llvm::Instruction::isShift (unsigned Opcode) [inline, static]
Determine if the Opcode is one of the shift instructions.
Definition at line 101 of file Instruction.h.
bool llvm::Instruction::isTerminator () const [inline]
Definition at line 85 of file Instruction.h.
References getOpcode(), and isTerminator().
Referenced by llvm::TerminatorInst::classof(), isTerminator(), llvm::MemoryDependenceAnalysis::removeInstruction(), and SimplifyCondBranchToTwoReturns().
static bool llvm::Instruction::isTerminator (unsigned OpCode) [inline, static]
Definition at line 92 of file Instruction.h.
bool Instruction::isUsedOutsideOfBlock (const BasicBlock * BB) const
isUsedOutsideOfBlock - Return true if there are any uses of this instruction in blocks other than the specified block. Note that PHI nodes are considered to evaluate their operands in the corresponding predecessor block.
isUsedOutsideOfBlock - Return true if there are any uses of I outside of the specified block. Note that PHI nodes are considered to evaluate their operands in the corresponding predecessor block.
Definition at line 310 of file Instruction.cpp.
References llvm::dyn_cast(), llvm::PHINode::getIncomingBlock(), llvm::Value::use_begin(), and llvm::Value::use_end().
bool llvm::Instruction::mayHaveSideEffects () const [inline]
mayHaveSideEffects - Return true if the instruction may have side effects.
Note that this does not consider malloc and alloca to have side effects because the newly allocated memory is completely invisible to instructions which don't used the returned value. For cases where this matters, isSafeToSpeculativelyExecute may be more appropriate.
Definition at line 264 of file Instruction.h.
References mayThrow(), and mayWriteToMemory().
Referenced by llvm::isInstructionTriviallyDead(), llvm::isInTailCallPosition(), isSafePHIToSpeculate(), SpeculativelyExecuteBB(), and TryToSinkInstruction().
bool Instruction::mayReadFromMemory () const
mayReadFromMemory - Return true if this instruction may read memory.
Definition at line 330 of file Instruction.cpp.
References llvm::Call, getOpcode(), llvm::SPII::Load, and llvm::SPII::Store.
Referenced by GetLocation(), hasConcreteDefImpl(), llvm::isInTailCallPosition(), IsMemRefInstr(), llvm::Loop::makeLoopInvariant(), mayReadOrWriteMemory(), and TryToSinkInstruction().
bool llvm::Instruction::mayReadOrWriteMemory () const [inline]
mayReadOrWriteMemory - Return true if this instruction may read or write memory.
Definition at line 250 of file Instruction.h.
References mayReadFromMemory(), and mayWriteToMemory().
Referenced by llvm::AliasSetTracker::addUnknown(), llvm::AliasSet::aliasesUnknownInst(), llvm::AliasSetTracker::deleteValue(), and llvm::AliasSetTracker::removeUnknown().
bool Instruction::mayThrow () const
mayThrow - Return true if this instruction may throw an exception.
Definition at line 370 of file Instruction.cpp.
Referenced by mayHaveSideEffects().
bool Instruction::mayWriteToMemory () const
mayWriteToMemory - Return true if this instruction may modify memory.
Definition at line 350 of file Instruction.cpp.
References llvm::Call, getOpcode(), llvm::SPII::Load, and llvm::SPII::Store.
Referenced by llvm::FindAvailableLoadedValue(), FindInitTrampolineFromBB(), GetLocation(), isFoldedOrDeadInstruction(), IsMemRefInstr(), isSafeToMove(), mayHaveSideEffects(), and mayReadOrWriteMemory().
void Instruction::moveBefore (Instruction * MovePos)
moveBefore - Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
Definition at line 90 of file Instruction.cpp.
References llvm::BasicBlock::getInstList(), and getParent().
Referenced by llvm::SCEVExpander::hoistIVInc(), llvm::Loop::makeLoopInvariant(), NegateValue(), llvm::NVPTXAllocaHoisting::runOnFunction(), TryToSinkInstruction(), llvm::InstCombiner::visitAllocaInst(), and llvm::InstCombiner::visitSelectInstWithICmp().
void Instruction::removeFromParent ()
removeFromParent - This method unlinks 'this' from the containing basic block, but does not delete it.
Definition at line 67 of file Instruction.cpp.
References llvm::BasicBlock::getInstList(), and getParent().
void llvm::Instruction::setDebugLoc (const DebugLoc & Loc) [inline]
setDebugLoc - Set the debug location information for this instruction.
Definition at line 174 of file Instruction.h.
Referenced by clone(), llvm::ConvertDebugDeclareToDebugValue(), ConvertShiftToMul(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::InstCombiner::InsertNewInstWith(), and llvm::IRBuilderBase::SetInstDebugLocation().
void llvm::Instruction::setInstructionSubclassData (unsigned short D) [inline, protected]
Definition at line 377 of file Instruction.h.
Referenced by llvm::CmpInst::setPredicate().
void Instruction::setMetadata (unsigned KindID, MDNode * Node)
setMetadata - Set the metadata of the specified kind to the specified node. This updates/replaces metadata if already present, or removes it if Node is null.
setMetadata - Set the metadata of of the specified kind to the specified node. This updates/replaces metadata if already present, or removes it if Node is null.
Definition at line 622 of file Metadata.cpp.
References llvm::SmallVectorTemplateCommon< T >::back(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::count(), llvm::SmallVectorBase::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::erase(), llvm::Value::getContext(), llvm::DebugLoc::getFromDILocation(), hasMetadata(), llvm::LLVMContext::MD_dbg, llvm::LLVMContextImpl::MetadataStore, llvm::LLVMContext::pImpl, llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by clone(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), llvm::FoldBranchToCommonDest(), llvm::RemapInstruction(), setMetadata(), llvm::BranchInst::swapSuccessors(), tryToMakeAllocaBePromotable(), and llvm::UpgradeIntrinsicCall().
void Instruction::setMetadata (StringRef Kind, MDNode * Node)
Definition at line 610 of file Metadata.cpp.
References llvm::Value::getContext(), hasMetadata(), and setMetadata().
Instruction* llvm::Instruction::use_back () [inline]
use_back - Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
Reimplemented from llvm::Value.
Definition at line 48 of file Instruction.h.
References llvm::Value::use_begin().
Referenced by DeadPHICycle(), llvm::DemoteRegToStack(), llvm::InstCombiner::DoOneIteration(), OptimizeGlobalAddressOfMalloc(), passingValueIsAlwaysUndefined(), ShouldBreakUpSubtract(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), tryToMakeAllocaBePromotable(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::InstCombiner::visitInsertElementInst(), llvm::InstCombiner::visitPHINode(), llvm::InstCombiner::visitSExt(), and llvm::InstCombiner::visitZExt().
const Instruction* llvm::Instruction::use_back () const [inline]
Reimplemented from llvm::Value.
Definition at line 49 of file Instruction.h.
References llvm::Value::use_begin().
Friends And Related Function Documentation
friend class SymbolTableListTraits< Instruction, BasicBlock > [friend]
Definition at line 370 of file Instruction.h.
The documentation for this class was generated from the following files:
Instruction.h
Instruction.cpp
Metadata.cpp